name: example
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  fb_auth: any
  subscription_holder: any
  provider: any
  firestore_ref:
    path: ..
# fb_authのために指定
dependency_overrides:
  firebase: ^7.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
  uses-material-design: true
