name: example
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  cupertino_icons: ^0.1.3
  subscription_holder: any
  provider: ^4.1.0-dev
  firebase_auth:
  firestore_ref:
    path: ..
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  freezed: any
  json_serializable: any
  pedantic_mono: any
flutter:
  uses-material-design: true
