name: example
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  cupertino_icons: ^0.1.3
  fb_auth: any
  subscription_holder: any
  provider: any
  firestore_ref:
    path: ..
# fb_authのために指定
dependency_overrides:
  firebase: ^7.2.1
  firebase_auth: ^0.15.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  freezed: any
  json_serializable: any
  pedantic_mono: any
flutter:
  uses-material-design: true
