name: firestore_ref
description: Firestore reference/document typed acccess helpers. You can write organized safe code by this.
version: 0.1.0
author: Masayuki Ono <mono0926@gmail.com>
homepage: https://github.com/mono0926/flutter_firestore_ref
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.12.9
  simple_logger: ^1.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter: