name: firestore_ref
description: Firestore reference/document typed acccess helpers. You can write organized safe code by this.
version: 0.8.0-dev+18
homepage: https://github.com/mono0926/flutter_firestore_ref
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.4+2
  firebase: ^7.2.1
  json_annotation: ^3.0.1
  simple_logger: ^1.6.0+1
  meta: ^1.1.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter: